seed_everything: 42

model:
  class_path: EventEgoPoseEstimation.modules.EventEgoPoseEstimation
  init_args:
    model_cfg:
      num_joints: 16
      eros: True
      input_channel: 20 #36 (works well in vis) #18 #12 #18
      posenet_input_channel: 20
      image_size: [256, 192]
      batch_size: 6 #16 # 9 # individual batch size

    lr: 0.0001
    lr_decay_epochs:
      - 22 #10
      - 27 #15
    
    loss_weights:
      bone_length: 0.001
      bone_orientation: 0.001
      j2d: 0.01
      j3d: 0.02
      heatmap: 10
      delta_j3d: 0.01
      seg: 0.1

    dataset_type:  real #synthetic # real
    training_type: finetune #finetune #pretrain # finetune
    use_bg_augmentation: true
    temporal_steps: 10
    sample_step: 10
    batch_size: 6
    workers: 15


ckpt_path: /CT/EventEgo3Dv2/work/EventEgo3Dv2/results/wandb_data/pretraining_new_dataloader_oom_fixed_5_2_2/EventEgo3Dv2/lmm6tavt/checkpoints/epoch=14.ckpt

trainer:
  accelerator: gpu
  max_epochs: 25
  check_val_every_n_epoch: 1
  devices: 4
  # num_nodes: 2
  benchmark: false
  # precision: 16-mixed
  strategy: ddp_find_unused_parameters_true
  fast_dev_run: false
  # limit_train_batches: 100
  # limit_val_batches: 1500
  # every_n_train_steps: 200
#  gradient_clip_val: 5.0
#  gradient_clip_algorithm: norm
  callbacks:
    - class_path: pytorch_lightning.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 50
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        every_n_epochs: 1
        save_top_k: -1
        filename: "{epoch}"
    - class_path: EventEgoPoseEstimation.modules.pose_estimation.EvaluateCallback
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        every_n_train_steps: 10000
        save_top_k: -1
        filename: "epoch_{epoch:02d}_step_{step}"
        # dirpath: "./results/"
        save_last: True
    # - class_path: pytorch_lightning.callbacks.LearningRateFinder

  logger:
  - class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      name: finetune_new_dataloader  # Experiment name on wandb
      project: EventEgo3Dv2  # Replace with your project name on wandb
      save_dir: ./results/wandb_data/finetune_new_dataloader  # Local directory to save wandb logs
      log_model: true  # Log the model checkpoints to wandb
      offline: false  # Set to true if you want to log offline and sync later
  - class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: ./results/
      name: finetune_new_dataloader  # TensorBoard experiment name
