seed_everything: 42

model:
  class_path: EventEgoPoseEstimation.modules.EventEgoPoseEstimation
  init_args:
    model_cfg:
      num_joints: 16
      eros: True
      input_channel: 18
      posenet_input_channel: 2
      image_size: [256, 192]
      batch_size: 16 #16 # 9 # individual batch size
      #heatmap_size: [config.MODEL.IMAGE_SIZE[0] // config.MODEL.HEAT_MAP_SCALE, config.MODEL.IMAGE_SIZE[1] // config.MODEL.HEAT_MAP_SCALE] TODO: fix this
    
    # dataset_cfg:
    #   dataset_type: synthetic # real, synthetic
    #   bg_aug: false
    #   real_root: /CT/datasets07/nobackup/EE3D-R/Real_Dataset
    #   syn_root: /CT/datasets07/nobackup/EE3D-S
    #   syn_test_root: /CT/datasets07/nobackup/EE3D-S-Test
    #   background_dataset_root: /CT/datasets07/nobackup/EE3D-R/Background_Dataset
    #   scale_factor: 0.2
    #   flip: true
    #   rot_factor: 3

    #   representaton: RawEvent
    #   event_batch_size: 4096
    lr: 0.001
    lr_decay_epochs:
      - 10
      - 15
    dataset_type: synthetic # real, synthetic
    training_type: pretrain # finetune
    temporal_steps: 1
    batch_size: 64
    workers: 16


# ckpt_path: /CT/EventEgo3Dv2/work/egoposeformer/results/pose3d/lightning_logs/version_68/checkpoints/epoch=11.ckpt
trainer:
  accelerator: gpu
  max_epochs: 20
  check_val_every_n_epoch: 1
  devices: 4
  benchmark: false
  precision: 16-mixed
  strategy: ddp_find_unused_parameters_true
  fast_dev_run: false
  # every_n_train_steps: 200
#  gradient_clip_val: 5.0
#  gradient_clip_algorithm: norm
  callbacks:
    - class_path: pytorch_lightning.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 50
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        every_n_epochs: 1
        save_top_k: -1
        filename: "{epoch}"
    - class_path: EventEgoPoseEstimation.modules.pose_estimation.EvaluateCallback
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        every_n_train_steps: 10000
        save_top_k: -1
        filename: "epoch_{epoch:02d}_step_{step}"
        # dirpath: "./results/"
        save_last: True

  logger:
    - class_path: pytorch_lightning.loggers.TensorBoardLogger
      init_args:
        save_dir: ./results/

# checkpoint_callback:
#   _target_: pytorch_lightning.callbacks.ModelCheckpoint
#   dirpath: "./results/"  # Directory to save checkpoints
#   filename: "epoch_{epoch:02d}_step_{step}"  # Naming format
#   save_top_k: -1  # Save all checkpoints (set to 1 if you want only the best one)
#   every_n_train_steps: 200  # Save after every 10,000 training steps
#   save_last: True  # Save the last checkpoint (optional)
    

