seed_everything: 50

model:
  class_path: EventEgoPoseEstimation.modules.EventEgoPoseEstimation
  init_args:
    model_cfg:
      num_joints: 16
      eros: True
      input_channel: 20 #36 (works well in vis) #18 #12 #18
      posenet_input_channel: 20
      image_size: [256, 192]
      batch_size: 9 #16 # 9 # individual batch size
      #heatmap_size: [config.MODEL.IMAGE_SIZE[0] // config.MODEL.HEAT_MAP_SCALE, config.MODEL.IMAGE_SIZE[1] // config.MODEL.HEAT_MAP_SCALE] TODO: fix this
    
    # dataset_cfg:
    #   dataset_type: synthetic # real, synthetic
    #   bg_aug: false
    #   real_root: /CT/datasets07/nobackup/EE3D-R/Real_Dataset
    #   syn_root: /CT/datasets07/nobackup/EE3D-S
    #   syn_test_root: /CT/datasets07/nobackup/EE3D-S-Test
    #   background_dataset_root: /CT/datasets07/nobackup/EE3D-R/Background_Dataset
    #   scale_factor: 0.2
    #   flip: true
    #   rot_factor: 3

    #   representaton: RawEvent
    #   event_batch_size: 4096
    lr: 0.001
    lr_decay_epochs:
      - 5 #10
      - 7 #15
    loss_weights:
      bone_length: 0.001
      bone_orientation: 0.001
      j2d: 0.01
      j3d: 0.02
      heatmap: 10
      delta_j3d: 0.01
      seg: 0.1

    dataset_type:  real #synthetic #synthetic # real
    training_type: finetune #pretrain #pretrain #finetune #pretrain # finetune
    use_bg_augmentation: false
    temporal_steps: 10
    sample_step: 5
    batch_size: 9
    workers: 14

    dataset:
      syn_preprocessed_input_path: /scratch/inf0/user/mdeshmuk/EE3D-preprocessed/EE3D-S
      real_preprocessed_input_path: "/scratch/inf0/user/mdeshmuk/EE3D-preprocessed/EE3D-R" 
      syn_dataset_root_path: /CT/datasets07/nobackup/EE3D-S
      syn_test_dataset_root_path: /CT/datasets07/nobackup/EE3D-S-Test
      real_dataset_root_path: /CT/datasets07/nobackup/EE3D-R/Real_Dataset



# ckpt_path: /CT/EventEgo3Dv2/work/EventEgo3Dv2/results/wandb_data/pretraining_new_dataloader_oom_fixed_5/EventEgo3Dv2/a48pwu92/checkpoints/epoch=6.ckpt
# ckpt_path: /CT/EventEgo3Dv2/work/EventEgo3Dv2/results/wandb_data/pretraining_new_dataloader_oom_fixed_5_1/EventEgo3Dv2/ha8vz1xf/checkpoints/epoch=9.ckpt

trainer:
  accelerator: gpu
  max_epochs: 1
  check_val_every_n_epoch: 1
  devices: 1
  # num_nodes: 2
  benchmark: false
  detect_anomaly: true
  # profiler: advanced
  # precision: bf16-mixed
  strategy: ddp_find_unused_parameters_true
  # strategy: ddp
  fast_dev_run: true
  # limit_train_batches: 200
  # limit_val_batches: 100
  # every_n_train_steps: 200
  # gradient_clip_val: 5
  # gradient_clip_algorithm: norm
  callbacks:
    - class_path: pytorch_lightning.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 50
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        every_n_epochs: 1
        save_top_k: -1
        filename: "{epoch}"
    # - class_path: EventEgoPoseEstimation.modules.pose_estimation.EvaluateCallback
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        every_n_train_steps: 10000
        save_top_k: -1
        filename: "epoch_{epoch:02d}_step_{step}"
        # dirpath: "./results/"
        save_last: True
    # - class_path: pytorch_lightning.callbacks.LearningRateFinder


  # logger:
  #   - class_path: pytorch_lightning.loggers.TensorBoardLogger
  #     init_args:
  #       save_dir: ./results/
  #       name: test # Experiment name

  logger:
  # - class_path: pytorch_lightning.loggers.WandbLogger
  #   init_args:
  #     name: test8  # Experiment name on wandb
  #     project: EventEgo3Dv2  # Replace with your project name on wandb
  #     save_dir: ./results/test8  # Local directory to save wandb logs
  #     log_model: true  # Log the model checkpoints to wandb
  #     offline: false  # Set to true if you want to log offline and sync later
  - class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: ./results/
      name: test  # TensorBoard experiment name
